---
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  namespace: grafana-operator
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  labels:
    dashboards: "grafana"
spec:
  config:
    log:
      mode: "console"
    auth:
      disable_login_form: "false"
    auth.anonymous:
      enabled: "true"
      org_role: "Admin"
    security:
      admin_user: admin
      admin_password: admin
      allow_embedding: "true"
  route:
    spec:
      to:
        kind: Service
        name: grafana-service
      port:
        targetPort: grafana
