---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-serviceaccount
  namespace: grafana-operator
  annotations:
    argocd.argoproj.io/sync-wave: "2"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: grafana-cluster-monitoring-view
  annotations:
    argocd.argoproj.io/sync-wave: "2"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-monitoring-view
subjects:
  - kind: ServiceAccount
    name: grafana-serviceaccount
    namespace: grafana-operator
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-datasource-token
  namespace: grafana-operator
  annotations:
    kubernetes.io/service-account.name: grafana-serviceaccount
    argocd.argoproj.io/sync-wave: "3"
type: kubernetes.io/service-account-token
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: prometheus-datasource
  namespace: grafana-operator
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
  datasource:
    name: Prometheus
    type: prometheus
    access: proxy
    url: https://thanos-querier.openshift-monitoring.svc.cluster.local:9091
    isDefault: true
    jsonData:
      "tlsSkipVerify": true
      "timeInterval": "5s"
      "httpHeaderName1": "Authorization"
    secureJsonData:
      "httpHeaderValue1": "Bearer ${BEARER_TOKEN}"
  valuesFrom:
    - targetPath: "secureJsonData.httpHeaderValue1"
      valueFrom:
        secretKeyRef:
          name: grafana-datasource-token
          key: token
