---
# Sync Wave: 8
# Description: Configure MetalLB with IP address pool
# IMPORTANT: Update the IP address range to match your network
apiVersion: metallb.io/v1beta1
kind: MetalLB
metadata:
  name: metallb
  namespace: metallb-system
  annotations:
    argocd.argoproj.io/sync-wave: "8"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: main-pool
  namespace: metallb-system
  annotations:
    argocd.argoproj.io/sync-wave: "8"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  addresses:
  - 192.168.1.200-192.168.1.210  # CHANGE THIS to match your network subnet
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: main-pool-l2-adv
  namespace: metallb-system
  annotations:
    argocd.argoproj.io/sync-wave: "8"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  ipAddressPools:
  - main-pool
